### PR TITLE
feat: allow GoogleAuth in GlobalOptions

### PR DESCRIPTION
**Pull request by proppy**
Fixes: googleapis/nodejs-googleapis-common#175.
Depends-on: googleapis/google-auth-library-nodejs/pull/803.

### CODE REVIEW

**Comment by bcoe** [comment]
@proppy left comments on google-auth-library-nodejs. tldr; I'd like to better understand the use-case before we  expose a lower level client in the API.

**Comment by proppy** [comment]
@bcoe let's discuss this in https://github.com/googleapis/nodejs-googleapis-common/issues/175 as I already started describing the usecases I'm after in the issue comments.

**Comment by bcoe** [comment]
@proppy apologize for this stalling, this something we'd like to kick back into motion?

**Comment by proppy** [comment]
@bcoe we have a workaround for it, so it's not urgent. But I still think this would be a good idea to allow this.

**Comment by bcoe** [comment]
@proppy this seems reasonable to me, given that OAuth2Client inherits from AuthClient.

Where I'm a little confused though, is I don't believe GoogleAuth does:

https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L97

So I'm wondering if this would actually address your issue?

**Comment by proppy** [comment]
> Where I'm a little confused though, is I don't believe GoogleAuth does

Yes, and that's what I was trying to fix with https://github.com/googleapis/google-auth-library-nodejs/pull/803 and this very CL :)

**Comment by JustinBeckwith** [comment]
I think I have this covered in #287 :)

**Pull request closed without merging**
